apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: quarkus-soap-service-2
  title: Servicio SOAP en Quarkus (Contract First)
  description: Crea un servicio SOAP usando Quarkus y quarkus-cxf a partir de un WSDL
  tags:
    - quarkus
    - soap
    - cxf
    - wsdl
spec:
  owner: equipo-integracion
  type: service
  parameters:

    - title: Configuración del servicio SOAP
      required:
        - serviceName
        - servicePackage
        - wsdlFile
        - wsdlFileContent
      properties:
        serviceName:
          title: Nombre del servicio
          type: string
          description: Nombre técnico del servicio (usado como nombre de carpeta)
        servicePackage:
          title: Paquete Java base
          type: string
          default: cl.ejemplo.soap.v1
          description: Paquete base donde estaran las clases Java
        wsdlFile:
          title: Nombre del archivo WSDL
          type: string
          default: consulta.wsdl
          description: El WSDL será ubicado en src/main/resources/wsdl/
        wsdlFileContent:
          title: Archivo WSDL (.wsdl)
          type: string
          format: data-url
          ui:widget: file
        xsdFileName1:
          type: string
          title: Nombre del primer XSD
          default: ConsultaRequest.xsd
        xsdFileContent1:
          type: string
          format: data-url
          title: Archivo XSD 1
          ui:widget: file
        xsdFileName2:
          type: string
          title: Nombre del segundo XSD
          default: ConsultaResponse.xsd
        xsdFileContent2:
          type: string
          format: data-url
          title: Archivo XSD 2
          ui:widget: file
        includeBinding:
          title: ¿Incluir archivo binding.xml personalizado?
          type: boolean
          default: true

    - title: Repositorio GitHub
      required:
        - githubOwner
      properties:
        githubOwner:
          title: Organización o usuario en GitHub
          type: string
          description: A qué organización o usuario se subirá el repositorio
        repoVisibility:
          title: Visibilidad del repositorio
          type: string
          enum:
            - public
            - private
          default: private

    - title: Información del catálogo
      required:
        - componentName
        - componentOwner
      properties:
        componentName:
          title: Nombre del componente
          type: string
          description: Nombre visible en el catálogo (puede incluir espacios)
        componentDescription:
          title: Descripción
          type: string
          description: Descripción del componente en el catálogo
        componentOwner:
          title: Owner (responsable)
          type: string
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: [User, Group]

  steps:

    - id: fetch-template
      name: Crear estructura base
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./
        values:
          serviceName: ${{ parameters.serviceName }}
          servicePackage: ${{ parameters.servicePackage }}
          componentName: ${{ parameters.componentName }}
          componentDescription: ${{ parameters.componentDescription }}
          componentOwner: ${{ parameters.componentOwner }}

    - id: write-wsdl
      name: Copiar WSDL
      action: my:write
      input:
        files:
          - path: src/main/resources/wsdl/${{ parameters.wsdlFile }}
            content: ${{ parameters.wsdlFileContent }}
            encoding: base64

    - id: write-xsd
      name: Copiar XSD (si fue cargado)
      if: ${{ parameters.xsdFile1Content && parameters.xsdFile2Content }}
      action: my:write
      input:
        files:
        - path: src/main/resources/xsd/${{ parameters.xsdFileName1 }}
          content: ${{ parameters.xsdFileContent1 }}
          encoding: base64
        - path: src/main/resources/xsd/${{ parameters.xsdFileName2 }}
          content: ${{ parameters.xsdFileContent2 }}
          encoding: base64

    - id: generar-clases-jaxb
      name: Generar clases JAXB desde WSDL
      action: my:generate-jaxb-classes
      input:
        {}

    - id: crear-directorios-java
      name: Crear carpetas del paquete Java
      action: my:write
      input:
        files:
          - path: src/main/java/${{ parameters.servicePackage | replace(".", "/") }}/ServicioBase.java
            content: |
              public class ServicioBase {
              // Clase generada automáticamente por el template
              }

    - id: copy-jaxb-classes
      name: Copiar clases JAXB al paquete Java
      action: my:copy-jaxb-classes
      input:
        servicePackage: ${{ parameters.servicePackage }}


    - id: write-binding
      name: Agregar archivo binding.xml (opcional)
      if: ${{ parameters.includeBinding }}
      action: my:write
      input:
        files:
          - path: src/main/resources/wsdl/binding.xml
            content: |
              <jaxws:bindings xmlns:jaxws="http://java.sun.com/xml/ns/jaxws"
                              xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
                              jaxws:version="2.0">
                <jaxws:bindings>
                  <jaxb:globalBindings>
                    <jaxb:serializable uid="1" />
                  </jaxb:globalBindings>
                </jaxws:bindings>
              </jaxws:bindings>

    - id: publish
      name: Crear y subir repositorio en GitHub
      action: publish:github
      input:
        repoUrl: github.com?owner=${{ parameters.githubOwner }}&repo=${{ parameters.serviceName }}
        defaultBranch: main
        protectDefaultBranch: false
        repoVisibility: ${{ parameters.repoVisibility }}

    - id: register
      name: Registrar en catálogo de Backstage
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repositorio del servicio
        url: https://github.com/${{ parameters.githubOwner }}/${{ parameters.serviceName }}

